name: Compilar SnapLinux MP3 v3.2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Compilar en Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk xvfb

      - name: Instalar Librerías de Python
        run: pip install pyinstaller yt-dlp mutagen pillow

      - name: Compilar ejecutable (Linux)
        run: xvfb-run --server-args="-screen 0 1024x768x24" pyinstaller --onefile --windowed --name=snaplinux-mp3-linux snaplinux.py

      - name: Subir binario Linux
        uses: actions/upload-artifact@v4
        with:
          name: snaplinux-mp3-linux
          path: dist/snaplinux-mp3-linux

  build-windows:
    name: Compilar en Windows
    runs-on: windows-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Librerías de Python
        run: pip install pyinstaller yt-dlp mutagen pillow

      - name: Compilar ejecutable (Windows)
        run: pyinstaller --onefile --windowed --name=snaplinux-mp3-windows snaplinux.py

      - name: Subir binario Windows
        uses: actions/upload-artifact@v4
        with:
          name: snaplinux-mp3-windows.exe
          path: dist/snaplinux-mp3-windows.exe
